export const courses = [
  {
    id: 1,
    title: "Digital Marketing",
    description: "Master digital marketing strategies, SEO, social media marketing, and online advertising",
    duration: "6 months",
    students: 180,
    rating: 4.9,
    icon: "Globe",
    features: ["SEO & SEM", "Social Media Marketing", "Content Marketing", "Google Ads"],
    scheduleMale: "Monday, Tuesday - 11:00 AM to 1:00 PM",
    scheduleFemale: "Sunday - 10:00 AM to 1:00 PM",
    instructor: "Hamza Tariq",
    level: "Undergraduate",
    gender: ["both"],
    minEducation: "Intermediate",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 2,
    title: "English Language Course",
    description: "Improve your English speaking, writing, and communication skills",
    duration: "6 months",
    students: 200,
    rating: 4.7,
    icon: "BookOpen",
    features: ["Speaking Skills", "Writing Skills", "Grammar", "Business English"],
    schedule: "Monday, Tuesday - 2:00 PM to 4:00 PM",
    instructor: "Waqas Ahmad",
    level: "Matric Base",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 3,
    title: "Web & Mobile APP Development",
    description: "Learn to build modern web and mobile applications",
    duration: "8 months",
    students: 150,
    rating: 4.8,
    icon: "Code",
    features: ["HTML/CSS/JavaScript", "React.js", "React Native", "Node.js"],
    scheduleMale: [
      "Monday, Tuesday - 4:00 PM to 6:00 PM",
      "Saturday, Sunday - 7:00 PM to 9:00 PM"
    ],
    scheduleFemale: ["Monday, Tuesday - 2:00 PM to 4:00 PM"],
    instructor: "Ahmed Khan",
    level: "Intermediate to Advanced",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close"
  },
  {
    id: 4,
    title: "IT Professional",
    description: "Comprehensive IT training for professional certification",
    duration: "6 months",
    students: 120,
    rating: 4.6,
    icon: "Shield",
    features: ["CompTIA A+", "Network+", "Security+", "Linux"],
    schedule: "Tuesday, Thursday, Friday - 4:00 PM to 6:00 PM",
    instructor: "Usman Ali",
    level: "Beginner to Intermediate",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 5,
    title: "IT Support Engineer",
    description: "Become a certified IT support engineer",
    duration: "2-3 months",
    students: 90,
    rating: 4.5,
    icon: "Users",
    features: ["Hardware Support", "Software Support", "Network Support", "Customer Service"],
    scheduleMale: ["Decided soon"],
    instructor: "Ayesha Malik",
    level: "Beginner",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close"
  },
  {
    id: 6,
    title: "Web Designing Crash Course",
    description: "Quick web design course for beginners",
    duration: "4 months",
    students: 250,
    rating: 4.4,
    icon: "Database",
    features: ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
    scheduleMale: ["Saturday - 9:30 AM to 12:30 PM"],
    scheduleFemale: ["Saturday - 9:30 AM to 12:30 PM"],
    instructor: "Hassan Raza",
    level: "Beginner",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close"
  },
  {
    id: 7,
    title: "Oracle Apex Development",
    description: "Learn Oracle APEX for rapid application development",
    duration: "6 months",
    students: 80,
    rating: 4.3,
    icon: "Zap",
    features: ["Oracle Database", "APEX", "PL/SQL", "Web Development"],
    schedule: "Saturday - 5:00 PM to 8:00 PM",
    instructor: "Sana Ahmed",
    level: "Intermediate",
    gender: ["Male"],
    minEducation: "Graduation",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 8,
    title: "Graphic Designing",
    description: "Master graphic design with industry-standard tools",
    duration: "4 months",
    students: 160,
    rating: 4.7,
    icon: "GraduationCap",
    features: ["Adobe Photoshop", "Illustrator", "InDesign", "Typography"],
    scheduleMale: ["Thursday, Friday - 6:00 PM to 8:00 PM"],
    instructor: "Ali Raza",
    level: "All Levels",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Matriculation",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 9,
    title: "Video Animation",
    description: "Create stunning video animations and motion graphics",
    duration: "4 months",
    students: 110,
    rating: 4.6,
    icon: "Star",
    features: ["After Effects", "Premiere Pro", "Motion Graphics", "Video Editing"],
    scheduleMale: ["4:00 PM to 6:00 PM"],
    instructor: "Ahmed Khan",
    level: "Intermediate",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Intermediate + Adobe Photoshop",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 10,
    title: "3D Animation",
    description: "Learn 3D animation and modeling techniques",
    duration: "4 months",
    students: 70,
    rating: 4.8,
    icon: "Code",
    features: ["Blender", "Maya", "3D Modeling", "Animation"],
    scheduleMale: ["2:00 PM to 4:00 PM"],
    instructor: "Fatima Khan",
    level: "Advanced",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Intermediate + Adobe Photoshop & Video Animation",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 11,
    title: "AI & Data Science",
    description: "Explore artificial intelligence and data science",
    duration: "10-12 months",
    students: 60,
    rating: 4.9,
    icon: "Zap",
    features: ["Python", "Machine Learning", "Deep Learning", "Data Analysis"],
    scheduleMale: ["Saturday, Sunday - 5:00 PM to 7:00 PM"],
    instructor: "Dr. Ayesha Malik",
    level: "Advanced",
    genderType: "male",
    gender: ["Male"],
    minEducation: "Bachelor's",
    admissionStatus: "Close",
    genderType: "male",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 201,
    title: "Digital Marketing",
    description: "Master digital marketing strategies, SEO, social media marketing, and online advertising",
    duration: "6 months",
    students: 180,
    rating: 4.9,
    icon: "Globe",
    features: ["SEO & SEM", "Social Media Marketing", "Content Marketing", "Google Ads"],
    scheduleFemale: ["Sunday - 10:00 AM to 1:00 PM"],
    instructor: "Hamza Tariq",
    level: "Undergraduate",
    genderType: "female",
    gender: ["Female"],
    minEducation: "Intermediate",
    admissionStatus: "Close",
    classesPerWeek: 2,
    classDuration: '2 hours'
  },
  {
    id: 501,
    title: "Web Designing Crash Course",
    description: "Quick web design course for beginners",
    duration: "2 months",
    students: 250,
    rating: 4.4,
    icon: "Database",
    features: ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
    scheduleFemale: ["Wednesday - 2:00 PM to 5:00 PM"],
    instructor: "Miss Female",
    level: "Beginner",
    genderType: "female",
    gender: ["Female"],
    minEducation: "Matriculation",
    admissionStatus: "Close"
  },
  {
    id: 502,
    title: "Web & Mobile APP Development",
    description: "Learn to build modern web and mobile applications",
    duration: "10-12 months",
    students: 150,
    rating: 4.8,
    icon: "Code",
    features: ["HTML/CSS/JavaScript", "React.js", "React Native", "Node.js"],
    scheduleFemale: ["Saturday, Sunday - 1:00 PM to 3:00 PM"],
    instructor: "Miss Female",
    level: "Intermediate to Advanced",
    genderType: "female",
    gender: ["Female"],
    minEducation: "Matriculation",
    admissionStatus: "Close"
  },
  {
    id: 601,
    title: "Graphic Designing",
    description: "Master graphic design with industry-standard tools",
    duration: "4 months",
    students: 160,
    rating: 4.7,
    icon: "GraduationCap",
    features: ["Adobe Photoshop", "Illustrator", "InDesign", "Typography"],
    scheduleFemale: ["Saturday, Sunday - 1:00 PM to 3:00 PM"],
    instructor: "Miss Female",
    minEducation: "Intermediate",
    admissionStatus: "Close",
    genderType: "female",
    gender: ["Female"]
  },

]; 